[package]
name = "heapstore"
version = "0.1.0"
edition = "2024"
autobins = false
description = "Database Heap Table Storage Subsystem (UOL MSc project)"

[[bin]]
name = "bench"
path = "src/bin/bench.rs"

[[bin]]
name = "crash"
path = "src/bin/crash.rs"

[dependencies]
libc = "0.2"
io-uring = "0.7"

[profile.release]
debug = true

[workspace]
